/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideLinkedin: typeof import('~icons/lucide/linkedin')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconLucideMenu: typeof import('~icons/lucide/menu')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    IconMdiEmail: typeof import('~icons/mdi/email')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IconMdiMail: typeof import('~icons/mdi/mail')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiMoon: typeof import('~icons/mdi/moon')['default']
    IconMdiSun: typeof import('~icons/mdi/sun')['default']
    IconMdiX: typeof import('~icons/mdi/x')['default']
    IMdiEmail: typeof import('~icons/mdi/email')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
  }
}
